### ISSUE TITLE
缺字問題

### ISSUE THREAD

**Issue by leo424y** [twgo/lo2han#1]
https://youtu.be/RFX-dyMeTRY?t=54  lo2han  烏 碼 ⿰啥人   缺字有解嗎？
本機就顯示 ⿰  
若youtube也沒這個字或許就無解

**Comment by sih4sing5hong5** [comment]
本來就無漢字，這是我四五年前做的，毋過這馬毋是按呢做--ah
若有彼種的，直接用羅馬字

**Comment by leo424y** [comment]
哇賽，原來老大深耕這麼久了，我了解了，感謝回覆
